Repository ITU-BDSA2024-GROUP7/Chirp, pull requests merged in 2024-11, with the labels that each got.

#120 Fixed the Timezone
  src/Chirp.Infrastructure/Data/Cheep.db
  src/Chirp.Infrastructure/Repositories/CheepRepository.cs
Labels: Bug

#126 Test send cheeps
  .gitignore
  src/Chirp.Infrastructure/Data/Cheep.db
  src/Chirp.Infrastructure/Data/Cheep.db-shm
  src/Chirp.Infrastructure/Data/Cheep.db-wal
  test/Chirp.Test/E2ETests.cs
Labels: Bug, Testing

#128 Testing GitHub E2E tests
  .github/workflows/build_and_test.yml
  test/Chirp.Test/Chirp.Test.csproj
  test/Chirp.Test/E2ETests.cs
Labels: Testing

#129 Feature constraints
  src/Chirp.Infrastructure/Data/Cheep.db
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/Public.cshtml.cs
  src/Chirp.Web/Pages/Shared/_Layout.cshtml
  src/Chirp.Web/Pages/Shared/_ShareCheepForm.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  src/Chirp.Web/Pages/Views/SharedChirpViewModel.cs
Labels: Minor Feature

#130 Changed intial migration
  src/Chirp.Infrastructure/Data/Cheep.db-shm
  src/Chirp.Infrastructure/Data/Cheep.db-wal
  src/Chirp.Infrastructure/Migrations/20241002120734_InitialDBSchema.Designer.cs
  src/Chirp.Infrastructure/Migrations/20241002120734_InitialDBSchema.cs
Labels: Bug

#136 Enforce HSTS Header
  src/Chirp.Web/Program.cs
Labels: Minor Feature

#139 Bug fixing E2E test workflow
  .github/workflows/Publish.yml
  .github/workflows/build_and_test.yml
Labels: Testing

#138 Added CSP and CORS headers
  src/Chirp.Web/Program.cs
Labels: Enhancement

#146 Resolved warnings from current main
  src/Chirp.Infrastructure/Repositories/CheepRepository.cs
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/Public.cshtml.cs
  src/Chirp.Web/Pages/Shared/_ShareCheepForm.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  src/Chirp.Web/Pages/Views/SharedChirpViewModel.cs
  src/Chirp.Web/Program.cs
  test/Chirp.TestE2E/E2ETests.cs
Labels: Bug, Enhancement

#149 Enhancement CSS
  src/Chirp.Web/Areas/Identity/Pages/Account/Login.cshtml
  src/Chirp.Web/Areas/Identity/Pages/Account/Register.cshtml
  src/Chirp.Web/Pages/Shared/_Layout.cshtml
  src/Chirp.Web/Pages/Shared/_Navbar.cshtml
  src/Chirp.Web/wwwroot/css/identity.css
  src/Chirp.Web/wwwroot/css/style.css
  src/Chirp.Web/wwwroot/images/ArrowRightStartOnRectangle.svg
  src/Chirp.Web/wwwroot/images/GitHub-Symbol.png
  src/Chirp.Web/wwwroot/images/Home.svg
  src/Chirp.Web/wwwroot/images/PencilSquare.svg
  src/Chirp.Web/wwwroot/images/User.svg
  src/Chirp.Web/wwwroot/images/icon1.svg
  test/Chirp.TestE2E/E2ETests.cs
Labels: Enhancement

#152 Updated icon1.svg
  src/Chirp.Web/wwwroot/images/icon1.svg
Labels: Enhancement

#161 Added E2E Tests to test follow feature
  test/Chirp.TestE2E/E2ETests.cs
Labels: Testing

#169 Feature - User information page and download userdata
  src/Chirp.Core/Interfaces/ICheepRepository.cs
  src/Chirp.Infrastructure/Repositories/CheepRepository.cs
  src/Chirp.Infrastructure/Services/CheepService.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/DownloadPersonalData.cshtml
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/DownloadPersonalData.cshtml.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/ManageNavPages.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/PersonalData.cshtml
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/PersonalData.cshtml.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
  src/Chirp.Web/Chirp.Web.csproj
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/Public.cshtml.cs
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  src/Chirp.Web/Program.cs
Labels: Minor Feature

#175 Added a new endpoint to get the list of followers of the user + 3 new integration tests
  src/Chirp.Core/Interfaces/IAuthorRepository.cs
  src/Chirp.Infrastructure/Repositories/AuthorRepository.cs
  src/Chirp.Infrastructure/Services/CheepService.cs
  src/Chirp.Web/Program.cs
  test/Chirp.TestIntegration/IntegrationTests.cs
Labels: Testing

#176 Optimized visual layout for phones
  src/Chirp.Web/Chirp.Web.csproj
  src/Chirp.Web/Pages/Shared/_Layout.cshtml
  src/Chirp.Web/Pages/Shared/_Navbar.cshtml
  src/Chirp.Web/Pages/Shared/_ShareCheepForm.cshtml
  src/Chirp.Web/Pages/Shared/_mobileNavbar.cshtml
  src/Chirp.Web/wwwroot/css/identity.css
  src/Chirp.Web/wwwroot/css/mobile.css
  src/Chirp.Web/wwwroot/css/style.css
  src/Chirp.Web/wwwroot/images/icon1.svg
  src/Chirp.Web/wwwroot/images/icon1_2.svg
  src/Chirp.Web/wwwroot/images/register.svg
Labels: Enhancement

#185 Feature follower lists
  src/Chirp.Infrastructure/Repositories/AuthorRepository.cs
  src/Chirp.Infrastructure/Services/CheepService.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/PersonalData.cshtml.cs
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  src/Chirp.Web/wwwroot/css/style.css
  test/Chirp.TestE2E/E2ETests.cs
Labels: Minor Feature

#189 Css background - Enhancement
  src/Chirp.Web/Pages/Shared/_Layout.cshtml
  src/Chirp.Web/wwwroot/css/style.css
  src/Chirp.Web/wwwroot/images/Day.png
  src/Chirp.Web/wwwroot/images/DayGradient.png
  src/Chirp.Web/wwwroot/images/Night.png
  src/Chirp.Web/wwwroot/images/NightGradient.png
Labels: Enhancement

#190 Quick fix
  src/Chirp.Web/wwwroot/css/style.css
Labels: Enhancement

#196 Fixed Not showing posted Cheep's Text in downloadable file
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/DownloadPersonalData.cshtml.cs
Labels: Bug

#192 Feature delete cheep
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/Public.cshtml.cs
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  src/Chirp.Web/wwwroot/css/style.css
  src/Chirp.Web/wwwroot/images/trash-can-svgrepo-com.svg
  test/Chirp.TestE2E/E2ETests.cs
Labels: Enhancement, Minor Feature

#195 Dropdown for popular cheeps and newest cheep
  src/Chirp.Web/Pages/PopularTimeline.cshtml
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/Shared/_CheepSorting.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Program.cs
  src/Chirp.Web/wwwroot/css/mobile.css
  src/Chirp.Web/wwwroot/css/style.css
Labels: Enhancement

#197 Added A new Time Display
  src/Chirp.Core/DTOs/CheepDTO.cs
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/Public.cshtml.cs
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
Labels: Enhancement, Minor Feature

#198 Karma feature
  src/Chirp.Core/Interfaces/IAuthorRepository.cs
  src/Chirp.Infrastructure/Repositories/AuthorRepository.cs
  src/Chirp.Infrastructure/Services/CheepService.cs
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  src/Chirp.Web/wwwroot/css/style.css
Labels: Minor Feature

#203 New icon for deleting a Cheep
  src/Chirp.Web/Pages/PopularTimeline.cshtml
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/wwwroot/css/style.css
Labels: Minor Feature
