Repository ITU-BDSA2024-GROUP7/Chirp, pull requests merged in 2024-10, with the labels that each got.

#69 Fixed Di injection, And Added Razor page Support for cheepRepository
  .github/workflows/Publish.yml
  data/dump.sql
  data/schema.sql
  src/Chirp.Razor/Author.cs
  src/Chirp.Razor/Cheep.cs
  src/Chirp.Razor/Cheep.db
  src/Chirp.Razor/Cheep.db-shm
  src/Chirp.Razor/Cheep.db-wal
  src/Chirp.Razor/CheepDBContext.cs
  src/Chirp.Razor/CheepRepository.cs
  src/Chirp.Razor/CheepService.cs
  src/Chirp.Razor/Chirp.Razor.csproj
  src/Chirp.Razor/DBFacade.cs
  src/Chirp.Razor/DbInitializer.cs
  src/Chirp.Razor/Migrations/20241002120734_InitialDBSchema.Designer.cs
  src/Chirp.Razor/Migrations/20241002120734_InitialDBSchema.cs
  src/Chirp.Razor/Migrations/CheepDBContextModelSnapshot.cs
  src/Chirp.Razor/Pages/Public.cshtml
  src/Chirp.Razor/Pages/Public.cshtml.cs
  src/Chirp.Razor/Pages/UserTimeline.cshtml
  src/Chirp.Razor/Pages/UserTimeline.cshtml.cs
  src/Chirp.Razor/Program.cs
  src/Chirp.Razor/appsettings.json
  test/Chirp.Razor.test/Chirp.Razor.test.csproj
  test/Chirp.Razor.test/E2ETests.cs
  test/Chirp.Razor.test/UnitTests.cs
Labels: Major Feature

#82 Expanding functionality
  src/Chirp.Razor/Author.cs
  src/Chirp.Razor/Cheep.cs
  src/Chirp.Razor/Cheep.db
  src/Chirp.Razor/Cheep.db-shm
  src/Chirp.Razor/Cheep.db-wal
  src/Chirp.Razor/CheepRepository.cs
  src/Chirp.Razor/CheepService.cs
  src/Chirp.Razor/Pages/Public.cshtml
  src/Chirp.Razor/Pages/Public.cshtml.cs
  src/Chirp.Razor/Pages/UserTimeline.cshtml
  src/Chirp.Razor/Pages/UserTimeline.cshtml.cs
Labels: Bug, Enhancement, Major Feature

#84 Fixed query method and pagination optimizations
  src/Chirp.Razor/Cheep.db
  src/Chirp.Razor/Cheep.db-shm
  src/Chirp.Razor/Cheep.db-wal
  src/Chirp.Razor/CheepRepository.cs
  src/Chirp.Razor/CheepService.cs
  src/Chirp.Razor/Pages/Public.cshtml
  src/Chirp.Razor/Pages/UserTimeline.cshtml
  src/Chirp.Razor/Pages/UserTimeline.cshtml.cs
  test/Chirp.Razor.test/E2ETests.cs
Labels: Bug, Enhancement

#98 Update README.md
  README.md
Labels: Documentation

#109 6 IDE warnings absolved
  src/Chirp.Infrastructure/Repositories/CheepRepository.cs
  src/Chirp.Infrastructure/Services/CheepService.cs
  src/Chirp.Web/Pages/Public.cshtml.cs
  src/Chirp.Web/Pages/Shared/_Navbar.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
Labels: Enhancement

#111 Feature send cheeps
  src/Chirp.Core/Author.cs
  src/Chirp.Core/Cheep.cs
  src/Chirp.Core/DTOs/CheepDTO.cs
  src/Chirp.Infrastructure/Chirp.Infrastructure.csproj
  src/Chirp.Infrastructure/Data/Cheep.db
  src/Chirp.Infrastructure/Migrations/20241031080055_UpdateAuthors.Designer.cs
  src/Chirp.Infrastructure/Migrations/20241031080055_UpdateAuthors.cs
  src/Chirp.Infrastructure/Repositories/CheepRepository.cs
  src/Chirp.Infrastructure/Services/CheepService.cs
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/Public.cshtml.cs
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  src/Chirp.Web/Program.cs
  src/Chirp.Web/appsettings.json
  test/Chirp.Test/IntegrationTests.cs
  test/Chirp.Test/UnitTests.cs
Labels: Major Feature

#112 Hot fix for Reaching DB in azure
  src/Chirp.Infrastructure/Data/Cheep.db
  src/Chirp.Infrastructure/Data/Cheep.db-shm
  src/Chirp.Infrastructure/Data/Cheep.db-wal
  src/Chirp.Web/appsettings.json
Labels: Bug

#113 Update Chirp.Infrastructure.csproj
  src/Chirp.Infrastructure/Chirp.Infrastructure.csproj
Labels: Bug

#114 Applied new migration to Cheep.DB
  src/Chirp.Infrastructure/Data/Cheep.db
  src/Chirp.Infrastructure/Data/Cheep.db-shm
  src/Chirp.Infrastructure/Data/Cheep.db-wal
Labels: Testing
