Repository ITU-BDSA2024-GROUP7/Chirp, pull requests merged in 2024-12, with the labels that each got.

#205 Have you ever seen an awesome Cheep That you wanted to Answer directly? Introducing Comments!
  src/Chirp.Core/DTOs/CheepDTO.cs
  src/Chirp.Infrastructure/Repositories/CheepRepository.cs
  src/Chirp.Infrastructure/Services/CheepService.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/DownloadPersonalData.cshtml.cs
  src/Chirp.Web/Pages/CheepComment.cshtml
  src/Chirp.Web/Pages/CheepComment.cshtml.cs
  src/Chirp.Web/Pages/PopularTimeline.cshtml
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/Public.cshtml.cs
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  src/Chirp.Web/Pages/Views/SharedChirpViewModel.cs
  src/Chirp.Web/wwwroot/css/style.css
  test/Chirp.TestE2E/E2ETests.cs
Labels: Enhancement, Major Feature

#207 Popular- and user-page now displays reactions properly.
  src/Chirp.Web/Pages/PopularTimeline.cshtml.cs
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
Labels: Enhancement

#213 Update README.md
  README.md
Labels: Documentation

#216 Fixed E2E test to use unicode instead
  test/Chirp.TestE2E/E2ETests.cs
Labels: Bug

#220 Bug fix css background
  src/Chirp.Web/Pages/Shared/_Layout.cshtml
  src/Chirp.Web/wwwroot/css/style.css
  src/Chirp.Web/wwwroot/js/background-gradient.js
Labels: Enhancement

#222 THE BIG WARNING CLEANUP
  src/Chirp.Core/DTOs/AuthorDTO.cs
  src/Chirp.Infrastructure/Repositories/CheepDBContext.cs
  src/Chirp.Infrastructure/Repositories/CheepRepository.cs
  src/Chirp.Infrastructure/Services/CheepService.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/DownloadPersonalData.cshtml.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/PersonalData.cshtml
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/PersonalData.cshtml.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Register.cshtml.cs
  src/Chirp.Web/Pages/CheepComment.cshtml
  src/Chirp.Web/Pages/CheepComment.cshtml.cs
  src/Chirp.Web/Pages/PopularTimeline.cshtml
  src/Chirp.Web/Pages/PopularTimeline.cshtml.cs
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/Public.cshtml.cs
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  test/Chirp.TestE2E/E2ETests.cs
Labels: Enhancement

#226 Bugfix for constraint bug in UserTimeline
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
Labels: Bug

#227 Added small buffer to gradient height
  src/Chirp.Web/wwwroot/js/background-gradient.js
Labels: Enhancement
